name: test-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test-lint:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: whisbi_test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out project
        uses: actions/checkout@v1
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap project
        run: npm run bootstrap
      - name: Compile project
        run: npm run compile
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
