name: test-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test-lint:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: whisbi_test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
    steps:
      - name: Check out project
        uses: actions/checkout@v1
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com
          always-auth: true
          scope: '@octopatas'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
