name: test-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v1
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Shutdown existing Ubuntu MySQL instance
        run: sudo service mysql stop
      - name: Set up MySQL
        uses: cweinberger/github-actions-mysql@1.0.0
        with:
          database: whisbi_test
          user: test
          password: test
      - name: Install dependencies
        run: npm ci
      - name: Bootstrap project
        run: npm run bootstrap
      - name: Compile project
        run: npm run compile
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm test
